//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("RiverSalaDB", "FK_Comentario_Usuario", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RiverSalaMVC.Usuario), "Comentario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RiverSalaMVC.Comentario), true)]
[assembly: EdmRelationshipAttribute("RiverSalaDB", "FK_Noticia_Usuario", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RiverSalaMVC.Usuario), "Noticia", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RiverSalaMVC.Noticia), true)]
[assembly: EdmRelationshipAttribute("RiverSalaDB", "FK_Comentario_Noticia", "Noticia", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RiverSalaMVC.Noticia), "Comentario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RiverSalaMVC.Comentario), true)]

#endregion

namespace RiverSalaMVC
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DB_38969_riversalaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DB_38969_riversalaEntities object using the connection string found in the 'DB_38969_riversalaEntities' section of the application configuration file.
        /// </summary>
        public DB_38969_riversalaEntities() : base("name=DB_38969_riversalaEntities", "DB_38969_riversalaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DB_38969_riversalaEntities object.
        /// </summary>
        public DB_38969_riversalaEntities(string connectionString) : base(connectionString, "DB_38969_riversalaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DB_38969_riversalaEntities object.
        /// </summary>
        public DB_38969_riversalaEntities(EntityConnection connection) : base(connection, "DB_38969_riversalaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Comentario> Comentario
        {
            get
            {
                if ((_Comentario == null))
                {
                    _Comentario = base.CreateObjectSet<Comentario>("Comentario");
                }
                return _Comentario;
            }
        }
        private ObjectSet<Comentario> _Comentario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Noticia> Noticia
        {
            get
            {
                if ((_Noticia == null))
                {
                    _Noticia = base.CreateObjectSet<Noticia>("Noticia");
                }
                return _Noticia;
            }
        }
        private ObjectSet<Noticia> _Noticia;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuario
        {
            get
            {
                if ((_Usuario == null))
                {
                    _Usuario = base.CreateObjectSet<Usuario>("Usuario");
                }
                return _Usuario;
            }
        }
        private ObjectSet<Usuario> _Usuario;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Comentario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComentario(Comentario comentario)
        {
            base.AddObject("Comentario", comentario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Noticia EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNoticia(Noticia noticia)
        {
            base.AddObject("Noticia", noticia);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuario(Usuario usuario)
        {
            base.AddObject("Usuario", usuario);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RiverSalaDB", Name="Comentario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comentario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Comentario object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="idUsuario">Initial value of the IdUsuario property.</param>
        /// <param name="texto">Initial value of the Texto property.</param>
        /// <param name="fecha">Initial value of the Fecha property.</param>
        /// <param name="idNoticia">Initial value of the IdNoticia property.</param>
        public static Comentario CreateComentario(global::System.Int32 id, global::System.Int32 idUsuario, global::System.String texto, global::System.DateTime fecha, global::System.Int32 idNoticia)
        {
            Comentario comentario = new Comentario();
            comentario.ID = id;
            comentario.IdUsuario = idUsuario;
            comentario.Texto = texto;
            comentario.Fecha = fecha;
            comentario.IdNoticia = idNoticia;
            return comentario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                OnIdUsuarioChanging(value);
                ReportPropertyChanging("IdUsuario");
                _IdUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdUsuario");
                OnIdUsuarioChanged();
            }
        }
        private global::System.Int32 _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.Int32 value);
        partial void OnIdUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Texto
        {
            get
            {
                return _Texto;
            }
            set
            {
                OnTextoChanging(value);
                ReportPropertyChanging("Texto");
                _Texto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Texto");
                OnTextoChanged();
            }
        }
        private global::System.String _Texto;
        partial void OnTextoChanging(global::System.String value);
        partial void OnTextoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdNoticia
        {
            get
            {
                return _IdNoticia;
            }
            set
            {
                OnIdNoticiaChanging(value);
                ReportPropertyChanging("IdNoticia");
                _IdNoticia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdNoticia");
                OnIdNoticiaChanged();
            }
        }
        private global::System.Int32 _IdNoticia;
        partial void OnIdNoticiaChanging(global::System.Int32 value);
        partial void OnIdNoticiaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RiverSalaDB", "FK_Comentario_Usuario", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("RiverSalaDB.FK_Comentario_Usuario", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("RiverSalaDB.FK_Comentario_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("RiverSalaDB.FK_Comentario_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("RiverSalaDB.FK_Comentario_Usuario", "Usuario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RiverSalaDB", "FK_Comentario_Noticia", "Noticia")]
        public Noticia Noticia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Noticia>("RiverSalaDB.FK_Comentario_Noticia", "Noticia").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Noticia>("RiverSalaDB.FK_Comentario_Noticia", "Noticia").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Noticia> NoticiaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Noticia>("RiverSalaDB.FK_Comentario_Noticia", "Noticia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Noticia>("RiverSalaDB.FK_Comentario_Noticia", "Noticia", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RiverSalaDB", Name="Noticia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Noticia : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Noticia object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="titulo">Initial value of the Titulo property.</param>
        /// <param name="contenido">Initial value of the Contenido property.</param>
        /// <param name="idUsuario">Initial value of the IdUsuario property.</param>
        /// <param name="fecha">Initial value of the Fecha property.</param>
        /// <param name="esPrivada">Initial value of the EsPrivada property.</param>
        public static Noticia CreateNoticia(global::System.Int32 id, global::System.String titulo, global::System.String contenido, global::System.Int32 idUsuario, global::System.DateTime fecha, global::System.Boolean esPrivada)
        {
            Noticia noticia = new Noticia();
            noticia.ID = id;
            noticia.Titulo = titulo;
            noticia.Contenido = contenido;
            noticia.IdUsuario = idUsuario;
            noticia.Fecha = fecha;
            noticia.EsPrivada = esPrivada;
            return noticia;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Contenido
        {
            get
            {
                return _Contenido;
            }
            set
            {
                OnContenidoChanging(value);
                ReportPropertyChanging("Contenido");
                _Contenido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Contenido");
                OnContenidoChanged();
            }
        }
        private global::System.String _Contenido;
        partial void OnContenidoChanging(global::System.String value);
        partial void OnContenidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                OnIdUsuarioChanging(value);
                ReportPropertyChanging("IdUsuario");
                _IdUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdUsuario");
                OnIdUsuarioChanged();
            }
        }
        private global::System.Int32 _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.Int32 value);
        partial void OnIdUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean EsPrivada
        {
            get
            {
                return _EsPrivada;
            }
            set
            {
                OnEsPrivadaChanging(value);
                ReportPropertyChanging("EsPrivada");
                _EsPrivada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EsPrivada");
                OnEsPrivadaChanged();
            }
        }
        private global::System.Boolean _EsPrivada;
        partial void OnEsPrivadaChanging(global::System.Boolean value);
        partial void OnEsPrivadaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RiverSalaDB", "FK_Noticia_Usuario", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("RiverSalaDB.FK_Noticia_Usuario", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("RiverSalaDB.FK_Noticia_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("RiverSalaDB.FK_Noticia_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("RiverSalaDB.FK_Noticia_Usuario", "Usuario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RiverSalaDB", "FK_Comentario_Noticia", "Comentario")]
        public EntityCollection<Comentario> Comentario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comentario>("RiverSalaDB.FK_Comentario_Noticia", "Comentario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comentario>("RiverSalaDB.FK_Comentario_Noticia", "Comentario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RiverSalaDB", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="apellidos">Initial value of the Apellidos property.</param>
        /// <param name="esJugador">Initial value of the EsJugador property.</param>
        /// <param name="activo">Initial value of the Activo property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static Usuario CreateUsuario(global::System.Int32 id, global::System.String nombre, global::System.String apellidos, global::System.Boolean esJugador, global::System.Boolean activo, global::System.String email, global::System.String password)
        {
            Usuario usuario = new Usuario();
            usuario.ID = id;
            usuario.Nombre = nombre;
            usuario.Apellidos = apellidos;
            usuario.EsJugador = esJugador;
            usuario.Activo = activo;
            usuario.Email = email;
            usuario.Password = password;
            return usuario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Apellidos
        {
            get
            {
                return _Apellidos;
            }
            set
            {
                OnApellidosChanging(value);
                ReportPropertyChanging("Apellidos");
                _Apellidos = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Apellidos");
                OnApellidosChanged();
            }
        }
        private global::System.String _Apellidos;
        partial void OnApellidosChanging(global::System.String value);
        partial void OnApellidosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean EsJugador
        {
            get
            {
                return _EsJugador;
            }
            set
            {
                OnEsJugadorChanging(value);
                ReportPropertyChanging("EsJugador");
                _EsJugador = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EsJugador");
                OnEsJugadorChanged();
            }
        }
        private global::System.Boolean _EsJugador;
        partial void OnEsJugadorChanging(global::System.Boolean value);
        partial void OnEsJugadorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Posicion
        {
            get
            {
                return _Posicion;
            }
            set
            {
                OnPosicionChanging(value);
                ReportPropertyChanging("Posicion");
                _Posicion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Posicion");
                OnPosicionChanged();
            }
        }
        private global::System.String _Posicion;
        partial void OnPosicionChanging(global::System.String value);
        partial void OnPosicionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Activo
        {
            get
            {
                return _Activo;
            }
            set
            {
                OnActivoChanging(value);
                ReportPropertyChanging("Activo");
                _Activo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Activo");
                OnActivoChanged();
            }
        }
        private global::System.Boolean _Activo;
        partial void OnActivoChanging(global::System.Boolean value);
        partial void OnActivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RiverSalaDB", "FK_Comentario_Usuario", "Comentario")]
        public EntityCollection<Comentario> Comentario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comentario>("RiverSalaDB.FK_Comentario_Usuario", "Comentario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comentario>("RiverSalaDB.FK_Comentario_Usuario", "Comentario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RiverSalaDB", "FK_Noticia_Usuario", "Noticia")]
        public EntityCollection<Noticia> Noticia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Noticia>("RiverSalaDB.FK_Noticia_Usuario", "Noticia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Noticia>("RiverSalaDB.FK_Noticia_Usuario", "Noticia", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
